### ISSUE TITLE
Elastic and Bubble animation change svg > path of other svg element on website and Menu don't animate then

### ISSUE THREAD

**Issue by KaweckiBartek** [negomi/react-burger-menu#431]
Hello

I have problem with menu animation in NextJs. On some page when i have other svg, the menu component is animating wrong svg. It change the first path of svg and animate it. In my example its search icon. 
I tried to change in file  node_modules//react-burger-menu/dist/react-burger-menu.js and node_modules//react-burger-menu/lib/menuFactory.js  .createElement and add an Id or className but it doesn't work. 

I send you 3 screenshots from one page.
1) this is svg search icon 
2) Menu when is open on Bubble effect
3) Menu svg path is not changing when is Open or close

Please Help me because your Burger Menu is awesome and I don't want to change it for another  :)

![Screenshot 2021-01-04 at 12 08 36](https://user-images.githubusercontent.com/67326141/10352986
![Screenshot 2021-01-04 at 12 08 36](https://user-images.githubusercontent.com/67326141/103529912-ca353180-4e86-11eb-92f2-1b05428ea636.png)
![Screenshot 2021-01-04 at 12 18 29](https://user-images.githubusercontent.com/67326141/103529999-fcdf2a00-4e86-11eb-8823-f420d9db503a.png)

1-b2f64400-4e86-11eb-8fe2-f509b62fc64c.png)

**Comment by KaweckiBartek** [comment]
![Screenshot 2021-01-04 at 12 09 17](https://user-images.githubusercontent.com/67326141/103530648-146ae280-4e88-11eb-833b-0cb9d9a75392.png)

**Comment by negomi** [comment]
Wow, this was a very specific bug, thank you for finding it 😄 

I just published version `3.0.3` which contains a fix so it should work for you now.

**Comment by KaweckiBartek** [comment]
Hi Negomi :) 

I updated the new version, but the problem is still as it was.

**Comment by negomi** [comment]
Oh no! Ok, I'll take another look later.

**Comment by negomi** [comment]
Hey @KaweckiBartek,

I tried to reproduce this problem locally but I wasn't able to.

Do you have a link to your repo I can look at to help debug?

**Comment by kazerlelutin** [comment]
Hello, I have the same problem, with version 3.0.8.

**Comment by l4so** [comment]
Hi, I had the same issue. The solution was to make the header render after the Menu
